
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package xml.project.wsdl.cbwsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-12T13:24:05.592+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CentralnaBankaService",
                      portName = "CentralnaBankaPort",
                      targetNamespace = "http://www.project.xml/wsdl/CBwsdl",
                      wsdlLocation = "file:/C:/Fakultet/8. semestar/XML-project/XWS-Project/WEB-INF/wsdl/CentralnaBanka.wsdl",
                      endpointInterface = "xml.project.wsdl.cbwsdl.CentralnaBanka")
                      
public class CentralnaBankaImpl implements CentralnaBanka {

    private static final Logger LOG = Logger.getLogger(CentralnaBankaImpl.class.getName());

    /* (non-Javadoc)
     * @see xml.project.wsdl.cbwsdl.CentralnaBanka#acceptMT103(xml.project.mt103.MT103  mt103 )*
     */
    public xml.project.mt900.MT900 acceptMT103(xml.project.mt103.MT103 mt103) throws AcceptMT103Fault    { 
        LOG.info("Executing operation acceptMT103");
        System.out.println(mt103);
        try {
            xml.project.mt900.MT900 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AcceptMT103Fault("acceptMT103Fault...");
    }

    /* (non-Javadoc)
     * @see xml.project.wsdl.cbwsdl.CentralnaBanka#acceptMT102(xml.project.mt102.MT102  mt102 )*
     */
    public xml.project.mt900.MT900 acceptMT102(xml.project.mt102.MT102 mt102) throws AcceptMT102Fault    { 
        LOG.info("Executing operation acceptMT102");
        System.out.println(mt102);
        try {
            xml.project.mt900.MT900 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AcceptMT102Fault("acceptMT102Fault...");
    }

}
