
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package xml.project.wsdl.cbwsdl;

import java.util.logging.Logger;

import xml.project.globals.StatusCode;
import xml.project.mt102.MT102;
import xml.project.mt103.MT103;
import xml.project.mt910.MT910;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-19T14:18:45.242+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CentralnaBankaService",
                      portName = "CentralnaBankaPort",
                      targetNamespace = "http://www.project.xml/wsdl/CBwsdl",
                      wsdlLocation = "WebContent/WEB-INF/wsdl/CentralnaBanka.wsdl",
                      endpointInterface = "xml.project.wsdl.cbwsdl.CentralnaBanka")
                      
public class CentralnaBankaImpl implements CentralnaBanka {

    private static final Logger LOG = Logger.getLogger(CentralnaBankaImpl.class.getName());

    /* (non-Javadoc)
     * @see xml.project.wsdl.cbwsdl.CentralnaBanka#acceptMT103(MT103  mt103 )*
     */
    public MT910 acceptMT103(MT103 mt103) throws AcceptMT103Fault    { 
        LOG.info("Executing operation acceptMT103");
        System.out.println(mt103);
        try {
            MT910 _return = new MT910();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AcceptMT103Fault("acceptMT103Fault...");
    }

    /* (non-Javadoc)
     * @see xml.project.wsdl.cbwsdl.CentralnaBanka#acceptMT102(MT102  mt102 )*
     */
    public StatusCode acceptMT102(MT102 mt102) { 
        LOG.info("Executing operation acceptMT102");
        System.out.println(mt102);
        try {
            StatusCode _return = new StatusCode();
            _return.setMessage("AKO USPE IDEMO NA FRIZBI");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    public String TEST(){
    	return "RADI!???!";
    }
}
