package xml.project.wsdl.bwsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-19T14:18:53.515+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "FirmaBankaService", 
                  wsdlLocation = "file:/C:/Users/Alexandra/Documents/GitHub/XWS/XWS-SOAP/WEB-INF/wsdl/Banka.wsdl",
                  targetNamespace = "http://www.project.xml/wsdl/bwsdl") 
public class FirmaBankaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.project.xml/wsdl/bwsdl", "FirmaBankaService");
    public final static QName FirmaBanci = new QName("http://www.project.xml/wsdl/bwsdl", "FirmaBanci");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Alexandra/Documents/GitHub/XWS/XWS-SOAP/WEB-INF/wsdl/Banka.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FirmaBankaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Alexandra/Documents/GitHub/XWS/XWS-SOAP/WEB-INF/wsdl/Banka.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FirmaBankaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FirmaBankaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmaBankaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirmaBankaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirmaBankaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirmaBankaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FirmaBanci
     */
    @WebEndpoint(name = "FirmaBanci")
    public FirmaBanci getFirmaBanci() {
        return super.getPort(FirmaBanci, FirmaBanci.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaBanci
     */
    @WebEndpoint(name = "FirmaBanci")
    public FirmaBanci getFirmaBanci(WebServiceFeature... features) {
        return super.getPort(FirmaBanci, FirmaBanci.class, features);
    }

}
